import Link from "next/link";
import NavBar from "../components/NavBar";

export const metadata = {
  title: "Mi tienda con Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
