import Link from 'next/link'
import React from 'react'
export const metadata = {
  title: "Store Next js",
  description: "Generated by Next.js",
};
const Layout = ({ children }) => {
  return (
    <>
      <nav>
        <h3>Seccion tienda</h3>
      </nav>
      <ul>
        <li><Link href={"/tienda"}>Home</Link></li>
        <li><Link href={"/tienda/categorias"}>Categoria</Link></li>
        <li><Link href={"/tienda/productos"}>Productos</Link></li>
      </ul>
      {children}
    </>
  )
}

export default Layout